### ISSUE TITLE
keeps downloading

### ISSUE THREAD

**Issue by jokeris111** [matej0/external-csgo-cheat#1]
hello, i have issue with .exe it just keeps downloading offsets and won't open properly, what could cause this thing?

**Comment by matej0** [comment]
https://github.com/matej0/external-csgo-cheat/blob/main/externalh4ck/externalh4ck/Stuff.h#L35
i hardcoded this for myself. change it to your own path.

sri, 2. velj 2022. u 15:11 jokeris111 ***@***.***> napisao je:

**Comment by jokeris111** [comment]
Yeah I got it. Messed up with some signatures while trying to add triggerbot lol, and that wasn’t successfull

**Comment by jokeris111** [comment]
Thanks though

**Comment by matej0** [comment]
> 

you dont have to mess with signatures, just parse it from hazedumper ( m_iCrosshairID ) with the json parser.
